[package]
name = "noopsie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clinop = { git = "https://github.com/NopFault/clinop", branch = "master" }
regex = "1.10.3"
